require_relative 'config'
require_relative 'day_test'
require_relative 'month_test'
require_relative 'punch_clock_test'
require_relative 'remove_test'
require_relative 'halfblock_test'
require_relative 'module_test'
require_relative 'attributes_test'
